apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    env: prod
spec:
  containers:
  - image: dflickpivota/hello:latest
    name: hello
    ports:
    - containerPort: 8080
      protocol: TCP
