name: Build, push and deploy

on:
  release:
    types: [created]

jobs:
  build:
    name: Run job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: ./mvnw spring-boot:build-image --quiet

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the release version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Tag image
        run: docker tag hello:0.0.1-SNAPSHOT dflickpivota/hello:${{steps.vars.outputs.tag}}

      - name: Publish image
        run: docker push dflickpivota/hello:${{steps.vars.outputs.tag}}

      - name: Print image name
        run: echo dflickpivota/hello:${{steps.vars.outputs.tag}}

      - name: Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.KUBECONFIG_SA_GITHUB }}'
          context: default-context
        id: setcontext

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          images: docker.io/dflickpivota/hello:${{steps.vars.outputs.tag}}
          manifests: |
            .kubernetes/deploy.yml
          strategy: canary
          percentage: 50
