name: Build image and deploy to Kubernetes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    outputs:
      tag: ${GITHUB_SHA}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn spring-boot:build-image --file pom.xml --quiet -DskipTests
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag image
        run: docker tag hello:0.0.1-SNAPSHOT lemberski/hello:${GITHUB_SHA}
      - name: Publish image
        run: docker push lemberski/hello:${GITHUB_SHA}
      - name: Print image tag
        run: echo ${GITHUB_SHA}
  deploy:
    name: Deploy to Kubernetes
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.KUBECONFIG_SA_GITHUB }}'
          context: nlemberski-aws-tas
        id: setcontext
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          images: docker.io/lemberski/hello:${{needs.build.outputs.tag}}
          manifests: |
            deploy.yml
          strategy: canary
          percentage: 50
      - name: Print image name
        run: echo lemberski/hello:${{needs.build.outputs.tag}}

