name: Canary reject

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true

jobs:
  promote:
    name: Reject
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.KUBECONFIG_SA_GITHUB }}'
          context: default-context
        id: setcontext
      - name: Do reject
        uses: azure/k8s-deploy@v1
        with:
          images: docker.io/dflickpivota/hello:${{ github.event.inputs.image_tag }}
          manifests: |
            .kubernetes/deploy.yml
          strategy: canary
          action: reject