name: Canary deploy

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image name'
        required: true

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_SA_GITHUB }}
          context: nlemberski-aws-tas
        id: setcontext
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          images: docker.io/lemberski/hello:${GITHUB_SHA}
          manifests: |
            deploy.yml
          strategy: canary
          percentage: 50
