name: Promote canary release

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image name'
        required: true

jobs:
  promote:
    name: Promote
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_SA_GITHUB }}
          context: nlemberski-aws-tas
        id: setcontext
      - name: Do promote
        uses: azure/k8s-deploy@v1
        with:
          images: ${{ github.event.inputs.image }}"
          manifests: |
            deploy.yml
          strategy: canary
          action: promote