name: Push to TAS

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Release comment'
        required: false

jobs:
  build:
    name: Run job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: ./mvnw clean install --quiet

      - uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: tanzu
          cf_space: dev
          command: push -f ./manifest.yml