name: Push to TAS

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Release comment'
        required: false

jobs:
  build:
    name: Run job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update apt
        run: sudo apt-get update
      - name: Install cf-cli
        run: sudo apt-get install cf7-cli

      - name: Login on TAS
        run: cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o tanzu -s dev

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: ./mvnw clean install --quiet

      - name: Push to TAS
        run: cf push -f ./manifest.yml