name: Build image and deploy to Kubernetes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn spring-boot:build-image --file pom.xml --quiet -DskipTests
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag image
        run: docker tag hello:0.0.1-SNAPSHOT lemberski/hello:${GITHUB_SHA}
      - name: Publish image
        run: docker push lemberski/hello:${GITHUB_SHA}
  deploy:
    name: Deploy to Kubernetes
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Kubernetes context
        uses: azure/k8s-actions/k8s-set-context@master
        with:
          k8s-url: ${{ secrets.KUBECTL_SERVER }}
          k8s-secret: ${{ secrets.KUBECTL_SA_TOKEN }}
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          images: docker.io/lemberski/hello:${GITHUB_SHA}
          manifests: |
            deploy.yml
          strategy: canary
          percentage: 50

